export const API_ROUTES = {
    LOGIN: '/auth/login',
    CHATBOT: '/chatbot/message',
    DASHBOARD: '/dashboard',
    APPOINTMENTS: '/appointments',
    PATIENTS: '/patients',
    CATALOGS_TYPE: '/catalog-types',
    CATALOGS: '/catalogs',
    DOCTORS: '/doctors',
    SPECIALTIES: '/specialties',
    CALENDAR: '/appointments-calendar',
    DOCTOR_SCHEDULES: '/doctor-schedule',
    DOCTOR_SPECIALTIES: '/doctor-specialties',
    MEDICAL_RECORDS: '/medical-records',
    USERS: '/users',
    ROLES: '/roles',
    PERMISSIONS: '/role-option-permissions',
    OPTIONS: '/options',
};